### ISSUE TITLE
[Bug] The default "power mode" and "calendar events" indicators are not handled

### ISSUE THREAD

**Issue by PS1Online** [ThierryHFR/Big-Sur-StatusArea#95]
Using Gnome 42.5 with Xorg or Wayland under Ubuntu 22.04 LTS Desktop 64-bit, two default indicators are not handled and are the "power mode (balanced, power saver)" and "calendar events (e.g. Today: No events)".
A .gif image will show exactly the problem.

![Screencast from 24-05-2022 21 01 44](https://user-images.githubusercontent.com/28962652/170112946-26051b1b-f072-4805-8930-682de5e7efd8.gif)

This is the extension configuration:

![BigSur](https://user-images.githubusercontent.com/28962652/201709520-18c30b7f-986a-488e-a78b-62f7b71dda1d.png)

Here is the list of my active plugins. Can you reproduce the problem?

![Enabled exentions](https://user-images.githubusercontent.com/28962652/201091980-83f161ea-52d4-45f3-a14b-4c40e1567045.png)

I have isolated the problem. I have disabled the extensions one at a time. There is a problem between the following two extensions enabled together:

![Conflicting extensions](https://user-images.githubusercontent.com/28962652/201098505-b7cbec4d-eacb-4e03-910e-08c2230562d6.png)

I discovered the exact cause of the problem and then adopted the workaround:

![simplescreenrecorder-2022-11-14_14 49 28](https://user-images.githubusercontent.com/28962652/201680839-d70ec38b-2cb5-40f8-897e-001b14bd2a6a.gif)

The solution to the problem is that your extension handles "power mode" and "calendar events" indicators.
Is this bugfix applicable? If yes, how long will it take?

**Comment by Ordissimo** [comment]
Hi @PS1Online ,
Can you tell me if I have a problem with Xorg?

**Comment by Ordissimo** [comment]
I tested on Ubuntu 22.04 64bits Wayland.
I don't reproduce, please give me the list of your extensions !

**Comment by blickers** [comment]
Comfirmed under X11, Gnome 42, Ubuntu 22.04.

**Comment by blickers** [comment]
Comfirmed under X11, Gnome 42, Ubuntu 22.04.

My list of installed extensions:

bigSur-StatusArea@ordissimo.com
blur-my-shell@aunetx
caffeine@patapon.info
dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com
ding@rastersoft.com
disconnect-wifi@kgshank.net
ibus-tweaker@tuberry.github.com
just-perfection-desktop@just-perfection
lunarcal@ailin.nemui
show-desktop-applet@valent-in
sound-output-device-chooser@kgshank.net
status-area-horizontal-spacing@mathematical.coffee.gmail.com
system-monitor@paradoxxx.zero.gmail.com
transparent-top-bar@ftpix.com
user-theme@gnome-shell-extensions.gcampax.github.com


Here are my all enabled extensions:
[extensions.tar.gz](https://github.com/Ordissimo/Big-Sur-StatusArea/files/9389979/extensions.tar.gz)

**Comment by Ordissimo** [comment]
Hi @blickers,
Thank you for your extensions!
Unfortunately I don't reproduce your problem:
[Capture vidéo du 22-08-2022 10:53:23.webm](https://user-images.githubusercontent.com/10682892/185881537-255f73e9-4137-4222-86b7-73d0d8554ea7.webm)

For info one of your extensions is not compatible:
![Capture d’écran du 2022-08-22 10-52-58](https://user-images.githubusercontent.com/10682892/185881576-aa4b9344-20f6-4bb0-87b2-ac67936b6b4d.png)

**Comment by blickers** [comment]
You need to click one of the indicator first (e.g. the volume icon), when the menu pops out, then move carefully between those indicator icons from left to right, form right to left (again and again...), and then, you will find the "hidden/lost" indicator of "power mode (balanced, power saver)", it's menu pops out! If you don't click, and you move to fast, you won't be able to find it.

**Comment by Kertrix** [comment]
Thanks!
It would be nice if the power mode was in the same menu as the power percentage.

**Comment by Kertrix** [comment]
Hi again! 
For me, Just Perfection is causing this:
![demonstration](https://user-images.githubusercontent.com/75695086/187272810-76be4a45-bc81-4305-8954-e65a8b16c80a.gif)
Good evening,

**Comment by luca-martino** [comment]
Same issue.

OS: Fedora release 36 (Thirty Six) x86_64
DE: GNOME 42.4

![immagine](https://user-images.githubusercontent.com/17565704/188653628-c25a542c-0db4-4f8d-987a-d7d9cc412afd.png)

**Comment by PS1Online** [comment]
> Hi @PS1Online , Can you tell me if I have a problem with Xorg?

Yes, even with Xorg, I will update the text of the problem.

**Comment by PS1Online** [comment]
> I tested on Ubuntu 22.04 64bits Wayland. I don't reproduce, please give me the list of your extensions !

Here is the list of my active plugins. Can you reproduce the problem?
![Enabled exentions](https://user-images.githubusercontent.com/28962652/201091980-83f161ea-52d4-45f3-a14b-4c40e1567045.png)

**Comment by PS1Online** [comment]
I have isolated the problem. I have disabled the extensions one at a time. There is a problem between the following two extensions enabled together:

![Conflicting extensions](https://user-images.githubusercontent.com/28962652/201098505-b7cbec4d-eacb-4e03-910e-08c2230562d6.png)

**Comment by PS1Online** [comment]
@Ordissimo Hi, 7 months since I made the bug explanation complete and detailed. Have you viewed it?

**Comment by natewind** [comment]
* Ubuntu 22.04
* GNOME 42

Same issue, here’s the fix I use:

```sh
uuid="bigSur-StatusArea@ordissimo.com"
extension="$HOME/.local/share/gnome-shell/extensions/$uuid/extension.js"

aggregate_old='Main.panel.statusArea.aggregateMenu.container.hide();'
aggregate_new='Main.panel.statusArea.aggregateMenu.actor.hide();'

date_old='Main.panel.statusArea.dateMenu.container.hide();'
date_new='Main.panel.statusArea.dateMenu.actor.hide();'

sed -i -e "s|$aggregate_old|$aggregate_new|" "$extension"
sed -i -e "s|$date_old|$date_new|"           "$extension"
```

I’m too busy to make a pull request. @ThierryHFR, would you please change those 2 lines?

**Comment by ThierryHFR** [comment]
> * Ubuntu 22.04
> 
>     * GNOME 42
> 
> 
> Same issue, here’s the fix I use:
> 
> ```shell
> uuid="bigSur-StatusArea@ordissimo.com"
> extension="$HOME/.local/share/gnome-shell/extensions/$uuid/extension.js"
> 
> aggregate_old='Main.panel.statusArea.aggregateMenu.container.hide();'
> aggregate_new='Main.panel.statusArea.aggregateMenu.actor.hide();'
> 
> date_old='Main.panel.statusArea.dateMenu.container.hide();'
> date_new='Main.panel.statusArea.dateMenu.actor.hide();'
> 
> sed -i -e "s|$aggregate_old|$aggregate_new|" "$extension"
> sed -i -e "s|$date_old|$date_new|"           "$extension"
> ```
> 
> I’m too busy to make a pull request. @ThierryHFR, would you please change those 2 lines?

Hi @natewind,
Thanks for your contribution

**Comment by natewind** [comment]
@ThierryHFR, you released version 48 after this, but didn’t include the change. Is that intentional?

**Comment by ThierryHFR** [comment]
> @ThierryHFR, you released version 48 after this, but didn’t include the change. Is that intentional?

No, that's a mistake on my part, I've just published version 49.

**Comment by natewind** [comment]
> No, that's a mistake on my part, I've just published version 49.

Ok, thanks!

**Comment by natewind** [comment]
Sorry, I can’t find it:

![image](https://github.com/ThierryHFR/Big-Sur-StatusArea/assets/30814650/55dec5f1-2488-4a01-b138-230f78afb8d3)

**Comment by ThierryHFR** [comment]
> Sorry, I can’t find it:
> 
> ![image](https://user-images.githubusercontent.com/30814650/273956874-55dec5f1-2488-4a01-b138-230f78afb8d3.png)

Wait, gnome validates!

![Screenshot_2023-10-10-17-00-17-940_org mozilla firefox](https://github.com/ThierryHFR/Big-Sur-StatusArea/assets/10682892/bb24179c-c524-4015-b01d-45b1f505c3b7)

**Comment by natewind** [comment]
Ah, ok, I didn’t know how it works :)

**Comment by PS1Online** [comment]
> The solution to the problem is that your extension handles "power mode" and "calendar events" indicators.

This bugfix simply made the "power mode" and "calendar events" menus disappear, instead of making them actively available through the extension. I had reported the "unmanaged menus" bug, which meant that they had to be managed (therefore with the icons visible as for all the other menus managed by the extension, unlike the bug where these icons were invisible), therefore with the possibility of being enabled or disabled (made to disappear) like any other managed menu from the extension.

Ultimately, I don't consider the applied bugfix as a resolution but as the strengthening of a lack of management of these two menus.

**I ask you to reopen the bug.**
